export const GET_WEATHER_DATA = "GET_WEATHER_DATA ";
export const GET_WEATHER_DATA_SUCCESS = "GET_WEATHER_DATA_SUCCESS ";
export const GET_WEATHER_DATA_ERROR = "GET_WEATHER_DATA_ERROR ";
export const GET_WEATHER_WEEK_DATA = "GET_WEATHER_WEEK_DATA ";
export const GET_WEATHER_WEEK_DATA_SUCCESS = "GET_WEATHER_WEEK_DATA_SUCCESS";
export const GET_WEATHER_WEEK_DATA_ERROR = "GET_WEATHER_WEEK_DATA_ERROR ";
